FinalFSpacerApp/Models/DriveCard.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalFSpacerApp.Models
{
    public class DriveCard
    {
        public string Model { get; set; }
        public string Ratio { get; set; }
        [Key]
        public string DriveNumber { get; set; }
        public string GearNumber { get; set; }

        //I'm not sure about how to do this. 
        public List<string> Models = new List<string> { "F85", "F110", "F135", "F155", "F175" };
    }
}

FinalFSpacerApp/Controllers/DriveCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalFSpacerApp.Data;
using FinalFSpacerApp.Models;

namespace FinalFSpacerApp.Controllers
{
    public class DriveCardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DriveCardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DriveCards
        public async Task<IActionResult> Index()
        {
            return View(await _context.DriveCards.ToListAsync());
        }

        // GET: DriveCards/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards
                .SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }

            return View(driveCard);
        }

        // GET: DriveCards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DriveCards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Model,Ratio,DriveNumber,GearNumber")] DriveCard driveCard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(driveCard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(driveCard);
        }

        // GET: DriveCards/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards.SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }
            return View(driveCard);
        }

        // POST: DriveCards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Model,Ratio,DriveNumber,GearNumber")] DriveCard driveCard)
        {
            if (id != driveCard.DriveNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driveCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriveCardExists(driveCard.DriveNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driveCard);
        }

        // GET: DriveCards/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driveCard = await _context.DriveCards
                .SingleOrDefaultAsync(m => m.DriveNumber == id);
            if (driveCard == null)
            {
                return NotFound();
            }

            return View(driveCard);
        }

        // POST: DriveCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var driveCard = await _context.DriveCards.SingleOrDefaultAsync(m => m.DriveNumber == id);
            _context.DriveCards.Remove(driveCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriveCardExists(string id)
        {
            return _context.DriveCards.Any(e => e.DriveNumber == id);
        }

        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchResults(SearchInputModel search)
        {

            var drivecard = await _context.DriveCards.ToListAsync();

            var filtered = drivecard.Where(d => d.Model == search.SearchModel ||
                                          d.Ratio == search.SearchRatio ||
                                          d.DriveNumber == search.SearchDriveNumber ||
                                          d.GearNumber == search.SearchGearNumber);

            return View(filtered);
        }
    }
}

FinalFSpacerApp/Views/DriveCards/Create.cshtml
@model FinalFSpacerApp.Models.DriveCard

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>DriveCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ratio" class="control-label"></label>
                <input asp-for="Ratio" class="form-control" />
                <span asp-validation-for="Ratio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearNumber" class="control-label"></label>
                <input asp-for="GearNumber" class="form-control" />
                <span asp-validation-for="GearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalFSpacerApp/Views/DriveCards/Delete.cshtml
@model FinalFSpacerApp.Models.DriveCard

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DriveCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ratio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ratio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DriveNumber" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalFSpacerApp/Views/DriveCards/Details.cshtml
@model FinalFSpacerApp.Models.DriveCard

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DriveCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ratio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ratio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DriveNumber">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FinalFSpacerApp/Views/DriveCards/Edit.cshtml
@model FinalFSpacerApp.Models.DriveCard

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DriveCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ratio" class="control-label"></label>
                <input asp-for="Ratio" class="form-control" />
                <span asp-validation-for="Ratio" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="DriveNumber" />
            <div class="form-group">
                <label asp-for="GearNumber" class="control-label"></label>
                <input asp-for="GearNumber" class="form-control" />
                <span asp-validation-for="GearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalFSpacerApp/Views/DriveCards/Index.cshtml
@model IEnumerable<FinalFSpacerApp.Models.DriveCard>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Model)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ratio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GearNumber)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ratio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GearNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DriveNumber">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DriveNumber">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DriveNumber">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FinalFSpacerApp/Views/DriveCards/Search.cshtml
@model FinalFSpacerApp.Models.SearchInputModel
@{
    ViewData["Title"] = "Search";
}


<form asp-controller="DriveCards" asp-action="SearchResults" method="post">
    <label asp-for="SearchModel">Search by Model</label>
    <input asp-for="SearchModel" type="text" /><br />
    <label asp-for="SearchRatio">Search by Ratio</label>
    <input asp-for="SearchRatio" type="text" /><br />
    <label asp-for="SearchDriveNumber">Search by Drive Number</label>
    <input asp-for="SearchDriveNumber" type="text" /><br />
    <label asp-for="SearchGearNumber">Search by Gear Number</label>
    <input asp-for="SearchGearNumber" type="text" /><br />


    <input type="submit" value="submit" /><br />
</form>

FinalFSpacerApp/Views/DriveCards/SearchResults.cshtml
@model IEnumerable<DriveCard>
@{
    ViewData["Title"] = "SearchResults";
}

<h2>SearchResults</h2>

@if (Model.Count() == 0)
{
    <p>No drive card matching those terms were found!</p>
}
else
{
    <p>The following drive cards were found:</p>
    <ul>
        @foreach (var d in Model)
        {
            <li>@d.Model : @d.Ratio : @d.DriveNumber : @d.GearNumber</li>

        }
    </ul>
}